name: SCANOSS Analysis
 
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
 
permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: read
 
jobs:
  scanoss-analysis:
    name: SCANOSS Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Run SCANOSS analysis
        id: scan
        uses: scanoss/code-scan-action@v1
        with:
          policies: copyleft, undeclared
